### ISSUE TITLE
Add ways to cover costs of running playplay.io.

### ISSUE THREAD

**Issue by dblock** [playplayio/playplay.io#2]
Current options are:
- A paid service where teams just pay monthlies (not per user, but per team), probably 100$ a year per team.
- A sponsorship with compny logo on playplay.io, probably 100$ a year.

Add your :+1: below for one or another or something else.

**Comment by andpoi** [comment]
Are you thinking of doing per user/per month?

**Comment by dblock** [comment]
@andpoi I am the _least_ inclined to make it per user per month, maybe teams per month, ideally a sponsorship type thing, not trying to make $$$ off this project.

**Comment by andpoi** [comment]
Seems like a great idea. I'm sure not everyone that uses slack is enough of a hobbyist to run their own.

**Comment by dblock** [comment]
I've rolled out a donation button, for 100$ a year you get a logo smack in the middle of playplay.io. Will track sponsors and expenses [here](https://github.com/playplayio/playplay.io/blob/gh-pages/EXPENSES.md).

Donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GEXDDK46JKGWN
